name: Symfony UX

on: [push, pull_request]

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Prettier
              run: |
                  yarn
                  yarn run prettier --check {src,test}/**/*.js --config .prettierrc.json

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Tests
              run: |
                  yarn
                  yarn test
