name: Test

on:
    pull_request:
    push:
        branches:
            - 'main'

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: 14 # lowest supported version

            - name: Install Yarn Dependencies
              run: yarn install

            - name: Run Biome
              run: yarn run ci

    js-dist-current:
        name: Check for un-built JS dist files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: 14 # lowest supported version

            - run: yarn install && yarn build

            - name: Check if js dist files are current
              run: |
                  if [[ -n $(git status --porcelain) ]]; then
                    echo "The Git workspace is unclean! Changes detected:"
                    git status --porcelain
                    git diff
                    exit 1
                  else
                    echo "The Git workspace is clean. No changes detected."
                  fi
    tests:
        name: Tests (Node.js ${{ matrix.node-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-versions: [ '14', '16', '18', '20', '22', '23' ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node ${{matrix.node-versions}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-versions}}

            - name: Install Yarn Dependencies
              run: yarn install

            - name: Tests
              run: yarn test
