name: Test

env:
    NODE_VERSION_LOWEST_SUPPORTED: 18

on:
    pull_request:
    push:
        branches:
            - 'main'

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION_LOWEST_SUPPORTED }} # lowest supported version
                  cache: 'pnpm'

            - name: Install Node.js Dependencies
              run: pnpm install

            - name: Run Biome
              run: pnpm run ci

    js-dist-current:
        name: Check for un-built JS dist files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION_LOWEST_SUPPORTED }} # lowest supported version
                  cache: 'pnpm'
                
            - run: pnpm install && pnpm run build

            - name: Check if js dist files are current
              run: |
                  if [[ -n $(git status --porcelain) ]]; then
                    echo "The Git workspace is unclean! Changes detected:"
                    git status --porcelain
                    git diff
                    exit 1
                  else
                    echo "The Git workspace is clean. No changes detected."
                  fi
    tests:
        name: Tests (Node.js ${{ matrix.node-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-versions: [ '18', '20', '22', '23' ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Node ${{matrix.node-versions}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-versions}}
                  cache: 'pnpm'

            - name: Install Node.js Dependencies
              run: pnpm install

            - name: Tests
              run: pnpm run test
